# Generated by Django 5.2.3 on 2025-06-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_price'),
    ]

    operations = [
    ]
